#' surr_rsq_rank
#'
#' @param object A object of class \code{"surr_rsq"} that is generated by the function \code{"surr_rsq"}.
#' It contains the following components: \code{surr_rsq}, \code{reduced_model}, \code{full_model}, and \code{data}.
#' @param data A data set contains the categorical responses, predictors.
#' @param avg.num The number of replication for the averaging of surrogate R-square.
#' @param var.set A list that contains a few sets. Each component of these sets represents the variables
#' that you want to examine for the contribution of goodness of fit. Then, for one component of this list,
#' a model will fit by removing the specified variables.
#' @param ... Additional optional arguments.
#'
#' @importFrom PAsso surrogate
#' @importFrom MASS polr
#' @importFrom scales percent
#'
#' @return An list that contains the contribution of Surrogate R-squared for each variable.
#' @examples
#' data("RedWine")
#' full_formula <- as.formula(quality ~ fixed.acidity + volatile.acidity + citric.acid
#' + residual.sugar + chlorides + free.sulfur.dioxide +
#' total.sulfur.dioxide + density + pH + sulphates + alcohol)
#' fullmodel <- polr(formula = full_formula,data=RedWine, method  = "probit")
#' select_model <-update(fullmodel, formula. = ". ~ . - fixed.acidity - citric.acid
#' - residual.sugar - density")
#' Rank_table <-surr_rsq_rank(object  = select_model,
#' data    = RedWine,
#' var.set = test_var_set,avg.num = 30)
#' Rank_table
#' @export
#'
#'
surr_rsq_rank <-
  function(object,
           data,
           avg.num = 30,
           var.set = NA,
           ...){
    # Header
    # object = mod_add_square_cubic
    # data = red_wine2
    # avg.num = 30
    # source("D:/Dropbox/1.Research/2.Surrogate/5.R_Packages/R-squared/1.R_packages/R2Cate/R/surr_rsq.R")

    # update(mod_full_white, formula. = ". ~ . - citric.acid - chlorides - total.sulfur.dioxide - density")

    final_model_formula <- eval(object$call[[2]])

    if (is.na(var.set)[1]) {
      # final_variables <- names(object$coefficients)
      final_variables <- attr(object$terms, "term.labels")
    } else {
      # test_lt <- list(c("volatile.acidity"),
                      # c("I(sulphates^2)", "I(sulphates^3)"),
                      # c("sulphates", "I(sulphates^2)", "I(sulphates^3)"))
      final_variables <- lapply(X = var.set, FUN = function(x) paste(x, collapse = "-"))
    }

    a <- length(final_variables)

    surr_rsq_full <-
      surr_rsq(model = object,
               full_model = object,
               data = data,
               avg.num)[[1]]

    result <- c()
    surr_rsq_temp <- c()

    for(i in 1:a){
      # update(final_model_formula,~.-final_variables[i])
      # Here has bug, some update cannot be execute so will trigger bug "object 'model_temp_for' not found"
      model_temp_for <- update(object, paste("~ . -", final_variables[i]))
      # model_temp <- polr(model_temp_for, data = data, method = "probit")
      surr_rsq_temp[i] <- surr_rsq(model_temp_for,
                                   object,
                                   data,
                                   avg.num)[[1]]
      result[i] <- percent((surr_rsq_full - surr_rsq_temp[i])/surr_rsq_full,0.01)
    }

    result_table <- cbind.data.frame(var_set=unlist(final_variables), surr_rsq_temp, result)
    names(result_table) <- c("Variable names","SurrogateR2","Importance")
    result_table <- result_table[order(result_table$SurrogateR2,decreasing = FALSE),]
    Ranking <- c(1:a)
    result_table$Ranking <- Ranking
    # save(result_table, file = "test")
    return(result_table)
  }

